import { notFound } from "next/navigation";
import { getLeadById } from "@/lib/leads/repository";

function recommendedAction(status: string, emergency: string, reviewStatus: string) { if (emergency === "Yes" && status === "New") return "Call immediately and confirm dispatch window for emergency service."; if (status === "Estimate Sent") return "Follow up on the estimate and offer next available appointment slot."; if (reviewStatus === "Ready to Send") return "Send review request now while the customer experience is still fresh."; if (status === "Completed") return "Confirm payment closeout and request a Google review."; return "Send a status update and schedule the next follow-up touchpoint."; }

export default async function LeadDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { lead, source } = await getLeadById(id);
  if (!lead) notFound();

  return <div className="space-y-6"><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h1 className="text-3xl font-bold text-slate-900">Lead Detail: {lead.customerName}</h1><p className="mt-2 text-slate-600">All lead data mapped from the 5 Star Plumbing Google Sheet model.</p><p className="mt-1 text-xs uppercase tracking-wide text-slate-500">Data source: {source === "google-sheets" ? "Live Google Sheet" : "Mock Fallback"}</p></section><section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 space-y-1 text-sm text-slate-700"><h2 className="font-semibold text-slate-900">Customer Contact</h2><p>{lead.phone}</p><p>{lead.email || "No email provided"}</p><p>{lead.serviceAddress}</p><p><span className="font-semibold">Role:</span> {lead.customerRole}</p></div><div className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 space-y-1 text-sm text-slate-700"><h2 className="font-semibold text-slate-900">Job & Sales Info</h2><p><span className="font-semibold">Property Type:</span> {lead.propertyType}</p><p><span className="font-semibold">Service Type:</span> {lead.serviceType}</p><p><span className="font-semibold">Emergency:</span> {lead.emergency}</p><p><span className="font-semibold">Urgency:</span> {lead.urgency}</p><p><span className="font-semibold">Lead Source:</span> {lead.leadSource}</p><p><span className="font-semibold">Estimate Amount:</span> ${lead.estimateAmount.toLocaleString()}</p><p><span className="font-semibold">Follow-Up Date:</span> {lead.followUpDate}</p><p><span className="font-semibold">Review Request Status:</span> {lead.reviewRequestStatus}</p><p><span className="font-semibold">Preferred Appointment:</span> {lead.preferredAppointmentTime}</p><p><span className="font-semibold">Photos Uploaded:</span> {lead.photosUploaded}</p></div></section><section className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="font-semibold text-slate-900">Job Description</h2><p className="mt-2 text-sm text-slate-700">{lead.jobDescription}</p></section><section className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="font-semibold text-slate-900">Customer & Internal Notes</h2><p className="mt-2 text-sm text-slate-700"><span className="font-semibold">Customer Notes:</span> {lead.customerNotes}</p><p className="mt-2 text-sm text-slate-700"><span className="font-semibold">Internal Notes:</span> {lead.internalNotes}</p></section><section className="rounded-xl border border-blue-100 bg-blue-50 p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Recommended Next Action</h2><p className="mt-2 text-sm text-slate-700">{recommendedAction(lead.status, lead.emergency, lead.reviewRequestStatus)}</p></section></div>;
}
